---
# This does not work for some weird reason.
#- name: Install HDFS & Yarn packages
#  yum:
#    name: '{{ item }}'
#    name: "hadoop"
#    state: installed
#    update_cache: yes
#  with_items:
#    - hadoop
#    - hadoop-hdfs
#   - hadoop-libhdfs
#    - hadoop-yarn
#    - hadoop-mapreduce
#    - hadoop-client
#    - openssl
#  tags: [hdfs-packages]

- name: Install HDFS & Yarn packages
  shell: "yum install -y hadoop hadoop-hdfs hadoop-libhdfs hadoop-yarn hadoop-mapreduce hadoop-client openssl"
  tags: [hdfs-packages]

- name: configure hadoop
  template:
    src: '{{ item }}.xml.j2'
    dest: '{{ hadoop_conf_dir }}/{{ item }}.xml'
  with_items:
    - core-site
  tags:
    - hadoop

- name: set JAVA_HOME in hadoop-env.sh
  lineinfile:
    dest: '{{ hadoop_conf_dir }}/hadoop-env.sh'
    line: 'export JAVA_HOME={{ java_home }}'
    regexp: '^export JAVA_HOME='
    insertbefore: 'export JAVA_HOME='
  tags:
    - hadoop
