- name: systemd start script
  template:
    src: '{{ script_name }}-systemd.j2'
    dest: '/etc/systemd/system/{{ script_name }}.service'
    owner: root
    group: root
    mode: 644
  tags: systemd

