---

- name: configure mapred
  template:
    src: mapred-site.xml.j2
    dest: '{{ hadoop_conf_dir }}/mapred-site.xml'
  tags:
    - hadoop
    - mapred
  notify:
    - restart mapred historyserver

- include: historyserver.yml
  when: '"mapred-historyserver" in group_names'
