---

- name: create hdfs datanode data directory
  file: path={{ hdfs_datanode_data_dir }} state=directory owner=hdfs group=hadoop
  when: hdfs_datanode_data_dirs is not defined
  tags: [hdfs]

- name: create hdfs datanode data directories
  file: path={{ item }} state=directory owner=hdfs group=hadoop
  with_items: hdfs_datanode_data_dirs
  when: hdfs_datanode_data_dirs is defined
  tags: [hdfs]

- name: create /var/run/
  file: path=/var/run/hdfs state=directory owner=hdfs group=hadoop
  when: "'hdfs-datanode' in group_names"

- include: ../../../includes/tasks/systemd.yml script_name='hdfs-datanode'
  tags: [hdfs]

- name: start hdfs datanode
  service: name=hdfs-datanode state=started enabled=yes
  tags: [hdfs]
