---

- name: Install Storm package
  yum: name=storm state=installed
  tags: [storm]

- name: Configure storm
  template: src='{{ item }}.j2' dest='{{ storm_conf_dir }}/{{ item }}' owner=root mode=0644
  with_items: [storm.yaml,storm-env.sh]
  tags: [storm]

- name: Create local dir for Storm
  file: path=/var/lib/storm owner=storm group=hadoop mode=0750 state=directory
  tags: [storm]

- include: ../../../includes/tasks/systemd.yml script_name='{{ item }}' 
  with_items: [storm-nimbus,storm-ui,storm-logviewer,storm-drpc]
  when: "'storm-nimbus' in group_names"
  tags: [storm]

- include: ../../../includes/tasks/systemd.yml script_name='storm-supervisor'
  when: "'storm-supervisor' in group_names"
  tags: [storm]
 
- name: Enable storm-nimbus services
  service: name={{ item }} state=started enabled=yes
  with_items: [storm-ui,storm-logviewer,storm-drpc,storm-nimbus]
  when: "'storm-nimbus' in group_names"
  tags: [storm]

- name: Enable storm-supervisor service
  service: name="storm-supervisor" state=started enabled=yes
  when: "'storm-supervisor' in group_names"
  tags: [storm]
