---
- name: touch the exclude file
  file: path='{{ hadoop_conf_dir }}/yarn.exclude' state=touch
  when: "'yarn-resourcemanager' in group_names"
  tags:
    - hadoop
    - yarn

- name: configure yarn
  template:
    src: '{{ item }}.j2'
    dest: '{{ hadoop_conf_dir }}/{{ item }}'
  with_items:
    - yarn-site.xml
    - fair-scheduler.xml
  tags:
    - hadoop
    - yarn
  notify:
    - restart yarn resourcemanager
    - restart yarn nodemanager

- name: Create Yarn log directory
  file: path=/var/log/yarn/ owner=yarn group=hadoop state=directory mode=0750
  tags: [yarn]

- include: ../../../includes/tasks/systemd.yml script_name='yarn-resourcemanager'
  when: "'yarn-resourcemanager' in group_names"
  tags: [yarn,yarn-resourcemanager]

- name: start yarn resourcemanager
  service: name=yarn-resourcemanager state=started enabled=yes
  when: "'yarn-resourcemanager' in group_names"
  tags: [yarn,yarn-resourcemanager]

- name: create yarn nodemanager local directory
  file: path={{ yarn_nodemanager_local_dir }} state=directory owner=yarn group=hadoop
  when: "'yarn-nodemanager' in group_names"
  tags: [yarn,yarn-nodemanager]

- include: ../../../includes/tasks/systemd.yml script_name='yarn-nodemanager'
  when: "'yarn-nodemanager' in group_names"
  tags: [yarn,yarn-nodemanager]

- name: start yarn nodemanager
  service: name=yarn-nodemanager state=started enabled=yes
  when: "'yarn-nodemanager' in group_names"
  tags: [yarn,yarn-nodemanager]
