- name: install prerequisities for HDP hosts
  yum: name={{item}} state=latest
  with_items:
    - wget
    - unzip
    - java

- name: Fix hostname
  hostname: name={{ inventory_hostname }}

- name: Create /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts
