- name: install prerequisities for HDP hosts
  yum: name={{item}} state=latest
  with_items:
    - wget
    - unzip
    - java

- name: Add HDP repository
  yum_repository:
    name: HDP-2.3.0.0
    description: "HDP Version - HDP-2.3.0.0"
    baseurl: http://public-repo-1.hortonworks.com/HDP/centos7/2.x/updates/2.3.0.0
    state: present
    gpgkey: http://public-repo-1.hortonworks.com/HDP/centos7/2.x/updates/2.3.0.0/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins

- name: Add HDP repository
  yum_repository:
    name: HDP-UTILS-1.1.0.20
    description: "HDP Utils Version - HDP-UTILS-1.1.0.20"
    baseurl: http://public-repo-1.hortonworks.com/HDP-UTILS-1.1.0.20/repos/centos7
    state: present
    gpgkey: http://public-repo-1.hortonworks.com/HDP/centos7/2.x/updates/2.3.0.0/RPM-GPG-KEY/RPM-GPG-KEY-Jenkins

- name: Fix hostname
  hostname: name={{ inventory_hostname }}

- name: Create /etc/hosts
  template: src=hosts.j2 dest=/etc/hosts
