---

- include: ../../../includes/tasks/systemd.yml script_name='mapred-historyserver'

- name: start mapred historyserver
  service: name=mapred-historyserver state=started enabled=yes
  tags:
    - mapred
    - mapred-historyserver
    - hadoop
