---

- name: configure mapred
  template:
    src: mapred-site.xml.j2
    dest: '{{ hadoop_conf_dir }}/mapred-site.xml'
  tags:
    - hadoop
    - mapred
  notify:
    - restart mapred historyserver

#- name: create mapred command
#  template:
#    src: bin/mapred.j2
#    dest: /usr/bin/mapred
#    mode: 0755
#  tags:
#    - hadoop
#    - mapred

- include: historyserver.yml
  when: '"mapred-historyserver" in group_names'
